### ISSUE TITLE
no managed file therefore tutorial is useless

### ISSUE THREAD

**Issue by zinqq** [NoClueWhoIAm/EmuTarkov_ESP_Plus#4]
there is no managed file when downloading therefore the tutorial is useless and makes no sense when all i have is random stuff and some .cs files

**Comment by nos4r3** [comment]
You can find those by going to your EmuTarkov installation folder EscapeFromTarkov_Data > Managed > **.dll

You can find those by going to your EmuTarkov installation folder EscapeFromTarkov_Data > Managed > **.dll

You can find those by going to your EmuTarkov installation folder EscapeFromTarkov_Data > Managed > **.dll

lol the managed file is pull from your own game folder the tutorial couldn't even been more clear even zero knowledge about coding stuff like me still can update it just fine
