### ISSUE TITLE
After SPT-AKI updated to 0.12.10.1.11661, I can not use it

### ISSUE THREAD

**Issue by uk8064** [NoClueWhoIAm/EmuTarkov_ESP_Plus#6]
The first issue was when I build the solution they said IsYourPlayer is not method, but anyway I could fix that to erase (). but and then I cannot use it

**Comment by NoClueWhoIAm** [comment]
Cheat will be updated once 12.11 SPT-AKI is released, this method will be fixed + other features implemented.
(Memory issue fix provided)

**Comment by ByYasin** [comment]
@NoClueWhoIAm Escape From Tarkov 0.12.11.7.15426
AKI-2.1.1 

published. Can this project be updated according to the version?
